name: Issue handle
on:
  issues:
    types: [opened, edited, milestoned]
jobs:
  handle:
    runs-on: ubuntu-latest
    steps:
      - name: get details
        run: |
          echo A comment on PR $NUMBER
        env:
          NUMBER: ${{ toJSON(github.event) }}


