name: Issue handle
on:
  issues:
    types: [opened, edited, milestoned]
jobs:
  handle:
    runs-on: ubuntu-latest
    steps:
      - name: get details
        run: |
          echo "Issue details"
          echo ${{ github.event.issue.number }}



