name: Issue handle
on:
  issues:
    types: [opened, edited, milestoned]
jobs:
  handle:
    runs-on: ubuntu-latest
    steps:
      - name: get details
        run: |
          echo "${{  toJSON(github) }}"
          echo ${{ github.event.issue }}



