name: testAndDeploy
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: get dependencies
        run: npm ci
      - name: run tests
        run: npm test
      - name: lintig
        run: |
          npm lint
          echo "Linting"
          echo "building"
          echo "deploying"








