name: testAndDeploy
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        
      - name: get dependencies
        run: npm ci

      - name: work
        run: |
          npm run lint
          npm test
          echo "Linting"
          echo "building"
          echo "deploying"








